apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    {{- include "jivas.labels" . | nindent 4 }}
spec:
  serviceName: "mongodb-headless"
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        {{- include "jivas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongodb
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--bind_ip"
            - "0.0.0.0"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.mongodb.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.mongodb.storage }}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  labels:
    app: mongodb
    {{- include "jivas.labels" . | nindent 4 }}
spec:
  ports:
    - port: 27017
  clusterIP: None
  selector:
    app: mongodb