apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jivas-shared-pvc
spec:
  accessModes:
    - ReadWriteMany # allow multiple pods to mount simultaneously
  resources:
    requests:
      storage: 10Gi # size of the claim (for EFS it's mostly informational)
  storageClassName: efs-sc # uses dynamic provisioning via EFS CSI driver
