{{- define "jivas.randomPassword" -}}
{{- randAlphaNum 32 | b64enc -}}
{{- end -}}

{{- define "jivas.randomTokenSecret" -}}
{{- randAlphaNum 50 -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: jivas-secrets
  labels:
    {{- include "jivas.labels" . | nindent 4 }}
type: Opaque
data:
  JIVAS_PASSWORD: {{ default (include "jivas.randomPassword" .) .Values.jivas.secrets.password | b64enc }}
  JIVAS_WEBHOOK_SECRET_KEY: {{ default (include "jivas.randomPassword" .) .Values.jivas.secrets.webhookSecretKey | b64enc }}
  JIVAS_TOKEN_SECRET: {{ default (include "jivas.randomPassword" .) .Values.jivas.secrets.tokenSecret | b64enc }}
  TOKEN_SECRET: {{ default (include "jivas.randomTokenSecret" .) .Values.jivas.secrets.plainTokenSecret | b64enc }}
{{- if eq .Values.jivas.config.fileInterface "s3" }}
  JIVAS_S3_BUCKET_NAME: {{ .Values.jivas.config.s3.bucketName | b64enc }}
  JIVAS_S3_REGION_NAME: {{ .Values.jivas.config.s3.regionName | b64enc }}
  JIVAS_S3_ACCESS_KEY_ID: {{ .Values.jivas.config.s3.accessKeyId | b64enc }}
  JIVAS_S3_SECRET_ACCESS_KEY: {{ .Values.jivas.config.s3.secretAccessKey | b64enc }}
{{- end }}