apiVersion: v1
kind: Service
metadata:
  name: jivas
  labels:
    {{- include "jivas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: jivas
  ports:
    {{- if .Values.service.ports.http }}
    - name: http
      port: {{ .Values.service.ports.http.port }}
      targetPort: {{ .Values.service.ports.http.targetPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.ports.https }}
    - name: https
      port: {{ .Values.service.ports.https.port }}
      targetPort: {{ .Values.service.ports.https.targetPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.ports.jvclient }}
    - name: jvclient
      port: {{ .Values.service.ports.jvclient.port }}
      targetPort: {{ .Values.service.ports.jvclient.targetPort }}
      protocol: TCP
    {{- end }}
    {{- if .Values.service.ports.jvstudio }}
    - name: jvstudio
      port: {{ .Values.service.ports.jvstudio.port }}
      targetPort: {{ .Values.service.ports.jvstudio.targetPort }}
      protocol: TCP
    {{- end }}