{{- if .Values.optionalServices.typesense.enabled }}
# First create the secret
apiVersion: v1
kind: Secret
metadata:
  name: typesense-secrets
  labels:
    {{- include "jivas.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $typesenseApiKey := "" }}
  
  {{- /* Try to get the existing secret API key */ -}}
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "typesense-secrets") }}
  {{- if and $existingSecret $existingSecret.data $existingSecret.data.TYPESENSE_API_KEY }}
    {{- /* Use the existing API key if it exists */ -}}
    {{- $typesenseApiKey = $existingSecret.data.TYPESENSE_API_KEY }}
  {{- else if .Values.optionalServices.typesense.apiKey }}
    {{- /* Use the specified API key if provided */ -}}
    {{- $typesenseApiKey = (.Values.optionalServices.typesense.apiKey | b64enc) }}
  {{- else }}
    {{- /* Generate a new random API key as last resort */ -}}
    {{- $typesenseApiKey = (randAlphaNum 32 | b64enc) }}
  {{- end }}
  TYPESENSE_API_KEY: {{ $typesenseApiKey }}
---
# Then create the StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: typesense
  labels:
    {{- include "jivas.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typesense
  template:
    metadata:
      labels:
        app: typesense
        {{- include "jivas.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: typesense
          image: typesense/typesense:26.0
          ports:
            - containerPort: 8108
          env:
            - name: TYPESENSE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: typesense-secrets
                  key: TYPESENSE_API_KEY
            - name: TYPESENSE_DATA_DIR
              value: "/data"
          volumeMounts:
            - name: typesense-persistent-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: typesense-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.optionalServices.typesense.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.optionalServices.typesense.storage }}
---
# And finally create the Service
apiVersion: v1
kind: Service
metadata:
  name: typesense
  labels:
    app: typesense
    {{- include "jivas.labels" . | nindent 4 }}
spec:
  selector:
    app: typesense
  ports:
    - protocol: TCP
      port: 8108
      targetPort: 8108
  type: ClusterIP
{{- end }}